# Simple workflow for deploying static content to GitHub Pages
name: Update repos in index.html from releases
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  workflow_run:
    workflows: ["Fetch latest repos"]
    types:
      - completed


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go run main.go -latest -save

      - name: move index.html
        run: |
          mkdir output
          mv index.html output/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
